name: My Test

on:
  issue_comment:
    types:
      - created

jobs:
  plop:
    name: "Plop"
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.comment.body == 'plop'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout Pull Request
        run: hub pr checkout "${{github.event.issue.number}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Configure GIT
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Update PR
        run: |
          export HEAD=$(git rev-parse HEAD)
          echo "HEAD is: ${HEAD}"
          export BASE_REF=$(hub api repos/dubzzz/gh-actions-playground/pulls/${{github.event.issue.number}} | jq ".base.ref" --raw-output)
          echo "BASE_REF is: ${BASE_REF}"
          export IS_DRAFT=$(hub api repos/dubzzz/gh-actions-playground/pulls/${{github.event.issue.number}} | jq ".draft" --raw-output)
          echo "IS_DRAFT is: ${IS_DRAFT}"
          if [[ "${IS_DRAFT}" != "true" ]]; then
            exit 1
          fi
          git reset --hard "${BASE_REF}"
          git cherry-pick "${HEAD}"
          git push --force
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
