name: My Test

on:
  issue_comment:
    types:
      - created

jobs:
  plop:
    name: "Plop"
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.comment.body == 'plop'
    steps:
      - name: Test
        run: |
          export BASE_REF=$(hub api repos/dubzzz/gh-actions-playground/pulls/${{github.event.issue.number}} | jq ".base.ref" --raw-output)
          echo "BASE_REF is: ${BASE_REF}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
